Fixed binutils build when using host gcc version >= 4.9.2 (at least on Fedora 21).
Binutils was complaining:

../bfd/bfd.h:304:75: error: right-hand operand of comma expression has
no effect [-Werror=unused-value]
   #define bfd_set_section_userdata(bfd, ptr, val) (((ptr)->userdata =
(val)),TRUE)

There currently is no "solution", so the workaround is to ignore this by using

--disable-werror

in the configure invocation.